global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "ingestion-api"
    static_configs:
      - targets: ["ingestion-api:8000"]

  - job_name: "processor-worker"
    static_configs:
      - targets: ["processor-worker:8000"]
